[package]
name = "noxfm-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
noxfm-proto.workspace = true
rustix = { version = "1", features = ["fs"] }
uzers = "0.12"
infer = "0.22"
mime_guess = "2"
walkdir = "2"
thiserror.workspace = true
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "gif", "webp", "bmp", "tiff", "ico"] }
png = "0.18"
md-5 = "0.10"

[dev-dependencies]
tempfile.workspace = true
